WeatherApp.WebUI/Models/ErrorViewModel.cs
namespace WeatherApp.WebUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherApp.WebUI/ViewModels/CityViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace WeatherApp.WebUI.ViewModels
{
    public class CityViewModel
    {
        [Required]
        [StringLength(60, MinimumLength = 3)]
        public string CityName { get; set; }
    }
}

WeatherApp.WebUI/Controllers/AccountController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WeatherApp.Application.Users.Commands.SignUpUser;

namespace WeatherApp.WebUI.Controllers
{
    public class AccountController : BaseController
    {
        public AccountController(IMediator mediator) : base(mediator)
        {
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction(nameof(AdministratorController.Index), typeof(AdministratorController).Name.Replace("Controller", string.Empty));
            return View();
        }

        [HttpPost]
        [Filters.ModelStateValidationFilter]
        public async Task<IActionResult> Login(LoginUserCommand command)
        {
            var result = await _mediator.Send(command);
            if (!result.Errors.Any())
                return RedirectToAction(nameof(AdministratorController.Index), typeof(AdministratorController).Name.Replace("Controller", string.Empty));
            else
            {
                ModelState.AddModelError("login", result.Errors.FirstOrDefault());
                return View();
            }
        }
    }
}

WeatherApp.WebUI/Controllers/AdministratorController.cs
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WeatherApp.Application.Cities.Commands.AddCity;
using WeatherApp.Application.Cities.Commands.UpdateCity;
using WeatherApp.Application.Weather.Queries.GetAllCitiesWeather;
using WeatherApp.WebUI.ViewModels;

namespace WeatherApp.WebUI.Controllers
{
    [Authorize]
    public class AdministratorController : BaseController
    {
        public AdministratorController(IMediator mediator) : base(mediator)
        {
        }

        public async Task<IActionResult> Index()
        {
            var result = await _mediator.Send(new GetAllCitiesWeatherQuery());
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> AddCity(CityViewModel viewModel)
        {
            var command = new AddCityCommand() { CityName = viewModel.CityName };
            var response = await _mediator.Send(command);
            if (response.Errors.Any())
                return BadRequest(response);
            else
                return PartialView("_WeatherItem", response.Result);
        }

        public async Task<IActionResult> UpdateCity()
        {
            var command = new UpdateWeatherCommand();
            var response = await _mediator.Send(command);
            return Ok();
        }
    }
}

WeatherApp.WebUI/Controllers/BaseController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace WeatherApp.WebUI.Controllers
{
    public abstract class BaseController : Controller
    {
        protected readonly IMediator _mediator;

        public BaseController(IMediator mediator)
        {
            _mediator = mediator;
        }
    }
}

WeatherApp.WebUI/Controllers/HomeController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Threading.Tasks;
using WeatherApp.Application.Weather.Queries.GetAllCitiesWeather;
using WeatherApp.WebUI.Models;

namespace WeatherApp.WebUI.Controllers
{
    public class HomeController : BaseController
    {
        public HomeController(IMediator mediator) : base(mediator)
        {
        }

        public async Task<IActionResult> Index()
        {
            var result = await _mediator.Send(new GetAllCitiesWeatherQuery());
            return View(result);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WeatherApp.WebUI/Views/Administrator/Index.cshtml
@model ICollection<WeatherApp.Application.Weather.Queries.GetAllCitiesWeather.CityWeatherPreview>
@using WeatherApp.WebUI.ViewModels;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col s6">
        <button id="addCity" data-target="modal-container" class="btn modal-trigger">Add city</button>
    </div>
    <div class="col s6">
        <button id="updateCities" class="btn">Update weather</button>
    </div>
</div>
<div class="section">
    <!--   Icon Section   -->
    <partial name="_CityCollection" model="@Model" />
</div>
<partial name="_AddCityForm" model="new CityViewModel()" />

@section scripts {

    <script>
        $(function () {
            $('#AddCityForm').submit(function (e) {
                e.preventDefault();
                var form = $('#AddCityForm');
                form.validate();
                if (form.valid()) {
                    $.post($('form').attr('action'), $('form').serialize(), function () {
                    }).done((data) => {
                        $('#cityCollection').append(data);
                        alert("City added");
                    }).fail((data) => {

                        var error = [...data.responseJSON.errors];
                        $('#error').text(error[0]);
                    })
                }
                else
                    alert("Not valid");

            })
        });
    </script>
}
<script>
    $(document).ready(function () {
        $('.modal').modal();
        $('#updateCities').click(function () {
            $.post("/Administrator/UpdateCity")
                .done((data) => {
                    alert("success")
                })
                .fail((data) => {
                    alert("fail update");
                })
        })
    });
</script>

WeatherApp.WebUI/Views/Home/Index.cshtml
@model ICollection<WeatherApp.Application.Weather.Queries.GetAllCitiesWeather.CityWeatherPreview>
@{
    ViewData["Title"] = "Home Page";
}
<div class="section">
    <!--   Icon Section   -->
    <partial name="_CityCollection" model="@Model" />
</div>

WeatherApp.WebUI/Views/Shared/_AddCityForm.cshtml
@model WeatherApp.WebUI.ViewModels.CityViewModel
<div id="modal-container" class="modal">
    <div class="modal-content">
        <form id="AddCityForm" asp-controller="Administrator" asp-action="AddCity">
            <div>
                <div class="row">
                    <div class="input-field col s12">
                        <input asp-for="CityName" id="city" name="CityName" type="text" class="validate">
                        <label asp-for="CityName">City</label>
                        <span asp-validation-for="CityName" class="text-danger"></span>
                    </div>
                </div>
                <span id="error"></span>
                <div class="row">
                    <button class="btn waves-effect waves-light" type="submit" id="submit" name="action">
                        Submit
                        <i class="material-icons right">send</i>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="modal-footer">
        <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
</div>

WeatherApp.WebUI/Views/Shared/_AdministratorLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AdministratorLayout</title>
</head>
<body>
</body>
</html>

WeatherApp.WebUI/Views/Shared/_CityCollection.cshtml
@model ICollection<WeatherApp.Application.Weather.Queries.GetAllCitiesWeather.CityWeatherPreview>
<div class="row" id="cityCollection">
    @foreach (var item in Model)
    {
        <partial name="_WeatherItem" model="item" />
    }
</div>

WeatherApp.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherApp</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <link rel="stylesheet" href="~/materialize/css/materialize.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="light-blue lighten-1" role="navigation">
            <div class="nav-wrapper container">
                <a id="logo-container" href="#" class="brand-logo">Logo</a>
                <ul class="right hide-on-med-and-down">
                    <li><a asp-action="Index" asp-controller="Administrator">Navbar Link</a></li>
                </ul>
                <ul id="nav-mobile" class="sidenav">
                    <li><a asp-action="Index" asp-controller="Administrator">Navbar Link</a></li>
                </ul>
                <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="page-footer orange">

        <div class="footer-copyright">
            <div class="container">
                Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Materialize</a>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
    <script src="~/materialize/js/init.js"></script>
    <script src="~/materialize/js/materialize.min.js"></script>
</body>
</html>

WeatherApp.WebUI/Views/Shared/_WeatherItem.cshtml
@model WeatherApp.Application.Weather.Queries.GetAllCitiesWeather.CityWeatherPreview
<div class="col s12 m4">
    <h2 class="center light-blue-text">@Model.Name</h2>
    <p>Date: @Model.LastUpdate.ToString("yyyy-MM-dd HH:mm")</p>
    <table>
        <tbody>
            <tr>
                <td>Temperature:</td>
                <td>@Model.Main.Temperature</td>
            </tr>
            <tr>
                <td>Humidity:</td>
                <td>@Model.Main.Humidity</td>
            </tr>
            <tr>
                <td>Pressure:</td>
                <td>@Model.Main.Pressure</td>
            </tr>
        </tbody>
    </table>
</div>